#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use std::sync::{Mutex, OnceLock};
use tracing::info;
use tracing_appender::non_blocking::WorkerGuard;
// SqlCpError enum variants generated by bindgen from sqlcrypt.h
use SqlCpError::{
    scp_err_InvalidArgument, scp_err_NotFound, scp_err_NotSupported, scp_err_Success,
};

// UTF-16 LE encoding of "Cosmian KMS EKM Provider".
// Per the SQL Crypto API spec, SqlCpStr.ws does NOT need to be
// null-terminated; the `cb` field (byte count) is the sole length authority.
// We include a trailing 0x0000 anyway as a safety measure in case any
// internal SQL Server code path reads past `cb`, but it must NOT be counted
// in `cb`.  The slice lives for the lifetime of this DLL load.
static PROVIDER_NAME_UTF16: &[u16] = &[
    0x43, 0x6F, 0x73, 0x6D, 0x69, 0x61, 0x6E, // C o s m i a n
    0x20, //  (space)
    0x4B, 0x4D, 0x53, // K M S
    0x20, //  (space)
    0x45, 0x4B, 0x4D, // E K M
    0x20, //  (space)
    0x50, 0x72, 0x6F, 0x76, 0x69, 0x64, 0x65, 0x72,   // P r o v i d e r
    0x0000, // safety null — NOT counted in cb
];
// Character count of the string proper (excludes the safety null above).
const PROVIDER_NAME_CHARS: usize = 24;

// Bindgen-generated types from sqlcrypt.h
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// ---------------------------------------------------------------------------
// Logging
//
// The rolling log file is written to:
//   %PROGRAMDATA%\Cosmian\EKM\logs\cosmian_ekm.log.<date>
// which on a typical Windows installation resolves to:
//   C:\ProgramData\Cosmian\EKM\logs\cosmian_ekm.log.<date>
//
// %PROGRAMDATA% is the correct root for a Windows service / DLL because
// SQL Server runs as a service account that has no user profile — only
// the machine-wide ProgramData directory is reliably writable.
//
// The companion configuration file should be placed at:
//   %PROGRAMDATA%\Cosmian\EKM\config.toml
// ---------------------------------------------------------------------------

/// Holds the `WorkerGuard` that keeps the non-blocking writer's background
/// thread alive.  Dropped (flushing all pending records) in
/// `SqlCryptFreeProvider`.
///
/// SQL Server may load and unload this DLL at its own discretion.  Each load
/// produces a fresh process image of the DLL with freshly-initialised statics,
/// so `OnceLock` naturally re-initialises on every DLL load without any
/// special handling.
static LOG_GUARD: OnceLock<Mutex<Option<WorkerGuard>>> = OnceLock::new();

/// Initialise the rolling-file subscriber exactly once.
/// Subsequent calls are no-ops.
fn init_logging() {
    // OnceLock::get_or_init guarantees the closure runs at most once even
    // under concurrent calls (e.g. two threads calling the provider entry
    // point simultaneously).
    LOG_GUARD.get_or_init(|| {
        // Resolve %PROGRAMDATA% at runtime so the code works regardless of
        // the Windows installation drive.
        let log_dir = std::env::var("PROGRAMDATA")
            .map(|p| {
                std::path::PathBuf::from(p)
                    .join("Cosmian")
                    .join("EKM")
                    .join("logs")
            })
            .unwrap_or_else(|_| std::path::PathBuf::from(r"C:\ProgramData\Cosmian\EKM\logs"));

        // Best-effort directory creation; if this fails the appender will
        // also fail and we fall through gracefully.
        let _ = std::fs::create_dir_all(&log_dir);

        let file_appender = tracing_appender::rolling::daily(&log_dir, "cosmian_ekm.log");
        let (non_blocking, guard) = tracing_appender::non_blocking(file_appender);

        tracing_subscriber::fmt()
            .with_writer(non_blocking)
            .with_max_level(tracing::Level::INFO)
            .with_ansi(false) // ANSI escape codes are meaningless in a plain log file
            .init();

        info!(
            log_dir = %log_dir.display(),
            "Cosmian EKM logging initialised"
        );

        Mutex::new(Some(guard))
    });
}

// ---------------------------------------------------------------------------
// Provider initialization
// ---------------------------------------------------------------------------

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptInitializeProvider() -> SqlCpError {
    init_logging();
    info!("SqlCryptInitializeProvider called");
    scp_err_Success
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptFreeProvider() -> SqlCpError {
    info!("SqlCryptFreeProvider called");
    // Drop the WorkerGuard so the background logging thread flushes and exits
    // cleanly before the DLL is unloaded.
    if let Some(cell) = LOG_GUARD.get() {
        if let Ok(mut guard) = cell.lock() {
            drop(guard.take());
        }
    }
    scp_err_Success
}

// ---------------------------------------------------------------------------
// Session management
// ---------------------------------------------------------------------------

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptOpenSession(
    p_auth: *const SqlCpCredential,
    p_sess: *mut SqlCpSession,
) -> SqlCpError {
    info!("SqlCryptOpenSession called");
    if p_sess.is_null() {
        return scp_err_InvalidArgument;
    }
    // Write a non-null sentinel as the session handle.
    // SQL Server passes this value back unchanged in every subsequent call;
    // we never dereference it until real session objects are implemented.
    let _ = p_auth;
    unsafe {
        *p_sess = 1usize as SqlCpSession;
    }
    scp_err_Success
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptCloseSession(p_sess: *mut SqlCpSession, f_abort: BOOLEAN) -> SqlCpError {
    info!("SqlCryptCloseSession called");
    // Nothing to free while session handles are sentinel values.
    let _ = (p_sess, f_abort);
    scp_err_Success
}

// ---------------------------------------------------------------------------
// Provider info
// ---------------------------------------------------------------------------

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptGetProviderInfo(p_provider_info: *mut SqlCpProviderInfo) -> SqlCpError {
    info!("SqlCryptGetProviderInfo called");
    if p_provider_info.is_null() {
        return scp_err_InvalidArgument;
    }
    unsafe {
        // Zero-initialise the entire struct first.  SQL Server allocates this
        // struct and passes a pointer; its contents are undefined.  Zeroing
        // ensures that implicit padding bytes (e.g. the byte after
        // SqlCpVersion.revision) are clean and that any future field SQL
        // Server might read but we haven't set is safely zero.
        std::ptr::write_bytes(p_provider_info, 0, 1);

        let info = &mut *p_provider_info;

        // Provider display name.
        // SqlCpStr.cb is the byte count of the string; SqlCpStr.ws is a
        // pointer to the UTF-16 data.  Per the API spec, ws does NOT need to
        // be null-terminated — cb is the sole length authority.
        info.name.cb = (PROVIDER_NAME_CHARS * size_of::<u16>()) as ULONG;
        info.name.ws = PROVIDER_NAME_UTF16.as_ptr() as *mut WCHAR;

        // Stable GUID that uniquely identifies this provider across DLL versions.
        // {C05A1A00-1001-4001-8001-000000000001}
        let mut guid = GUID::default();
        guid.Data1 = 0xC05A_1A00u32;
        guid.Data2 = 0x1001u16;
        guid.Data3 = 0x4001u16;
        guid.Data4 = [0x80, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01];
        info.guid = guid;

        // DLL version.  SQL Server stores this on the first successful
        // registration and validates it on every subsequent DLL load; the
        // value must therefore stay constant for a given installation.
        // Encoded as {major, minor, build, revision} = {1, 0, 0, 0}.
        let mut ver = SqlCpVersion::default();
        ver.major = 1;
        ver.minor = 0;
        info.version = ver;

        // SQL Crypto API version this provider was compiled against (from sqlcrypt.h:
        // x_scp_SqlCpVerMajor = 1, x_scp_SqlCpVerMinor = 1)
        let mut scp_ver = SqlCpVersion::default();
        scp_ver.major = 1;
        scp_ver.minor = 1;
        info.scpVersion = scp_ver;

        // Authentication type: "Other" because we authenticate via client
        // certificate configured in config.toml, not via SQL Server Basic
        // (username/password) credentials.
        info.authType = SqlCpAuthType::scp_auth_Other;

        // Symmetric key support: advertise Supported so SQL Server accepts
        // the provider.  Actual symmetric operations return scp_err_NotSupported
        // until implemented.
        info.symmKeySupport = SqlCpKeyFlagsBm::scp_kf_Supported as SqlCpKeyFlags;

        // Asymmetric key support: supported and exportable.
        info.asymmKeySupport = SqlCpKeyFlagsBm::scp_kf_Supported as SqlCpKeyFlags;

        // Thumbprint length in bytes.  The sample provider uses sizeof(GUID) = 16;
        // SQL Server appears to validate this value against sizeof(GUID).
        info.cbKeyThumbLen = size_of::<GUID>() as ULONG; // 16

        // We accept an external key name in CreateKey (used for KMS key lookup)
        info.fAcceptsKeyName = 1; // TRUE

        info!(
            name_cb = info.name.cb,
            symm_key_support = info.symmKeySupport,
            asymm_key_support = info.asymmKeySupport,
            cb_key_thumb_len = info.cbKeyThumbLen,
            scp_ver_major = info.scpVersion.major,
            scp_ver_minor = info.scpVersion.minor,
            "SqlCryptGetProviderInfo struct populated"
        );
    }
    scp_err_Success
}

// ---------------------------------------------------------------------------
// Provider algorithms
// ---------------------------------------------------------------------------

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptGetNextAlgorithmId(p_alg_id: *mut SqlCpAlgId) -> SqlCpError {
    info!("SqlCryptGetNextAlgorithmId called");
    // We have no statically-defined algorithm IDs: all key types are determined
    // at runtime by the KMS. Return NotFound to signal an empty enumeration,
    // which is a valid response (SQL Server simply records that the provider
    // has no built-in algorithm list).
    let _ = p_alg_id;
    scp_err_NotFound
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptGetAlgorithmInfo(
    alg_id: SqlCpAlgId,
    p_algorithm_info: *mut SqlCpAlgorithmInfo,
) -> SqlCpError {
    let _ = (alg_id, p_algorithm_info);
    info!("SqlCryptGetAlgorithmInfo called");
    scp_err_NotSupported
}

// ---------------------------------------------------------------------------
// Key management
// ---------------------------------------------------------------------------

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptCreateKey(
    p_sess: *const SqlCpSession,
    p_key_name: *const SqlCpStr,
    algid: SqlCpAlgId,
    key_flags: SqlCpKeyFlags,
    p_key_thumb: *mut SqlCpKeyThumbprint,
) -> SqlCpError {
    let _ = (p_sess, p_key_name, algid, key_flags, p_key_thumb);
    info!("SqlCryptCreateKey called");
    scp_err_NotSupported
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptDropKey(
    p_sess: *const SqlCpSession,
    p_key_thumb: *const SqlCpKeyThumbprint,
) -> SqlCpError {
    let _ = (p_sess, p_key_thumb);
    info!("SqlCryptDropKey called");
    scp_err_NotSupported
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptGetNextKeyId(
    p_sess: *const SqlCpSession,
    p_key_id: *mut SqlCpKeyId,
) -> SqlCpError {
    let _ = (p_sess, p_key_id);
    info!("SqlCryptGetNextKeyId called");
    // Return NotFound to signal an empty key enumeration (no keys provisioned yet).
    scp_err_NotFound
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptGetKeyInfoByKeyId(
    p_sess: *const SqlCpSession,
    key_id: SqlCpKeyId,
    p_key_info: *mut SqlCpKeyInfo,
) -> SqlCpError {
    let _ = (p_sess, key_id, p_key_info);
    info!("SqlCryptGetKeyInfoByKeyId called");
    // TODO: When implemented, follow the memory-management contract:
    // If p_key_info is NULL or the embedded SqlCpStr buffers are too small,
    // populate the `cb` fields with the required byte counts and return
    // scp_err_InsufficientBuffer.  Never allocate on behalf of the caller.
    scp_err_NotSupported
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptGetKeyInfoByThumb(
    p_sess: *const SqlCpSession,
    p_key_thumb: *const SqlCpKeyThumbprint,
    p_key_info: *mut SqlCpKeyInfo,
) -> SqlCpError {
    let _ = (p_sess, p_key_thumb, p_key_info);
    info!("SqlCryptGetKeyInfoByThumb called");
    // TODO: same InsufficientBuffer contract as GetKeyInfoByKeyId.
    scp_err_NotSupported
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptGetKeyInfoByName(
    p_sess: *const SqlCpSession,
    p_key_name: *const SqlCpStr,
    p_key_info: *mut SqlCpKeyInfo,
) -> SqlCpError {
    let _ = (p_sess, p_key_name, p_key_info);
    info!("SqlCryptGetKeyInfoByName called");
    // TODO: same InsufficientBuffer contract as GetKeyInfoByKeyId.
    scp_err_NotSupported
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptExportKey(
    p_sess: *const SqlCpSession,
    p_key_thumb: *const SqlCpKeyThumbprint,
    key_encryptor_thumb: *const SqlCpKeyThumbprint,
    blob_type: SqlCpKeyBlobType,
    p_key_blob: *mut SqlCpKeyBlob,
) -> SqlCpError {
    let _ = (
        p_sess,
        p_key_thumb,
        key_encryptor_thumb,
        blob_type,
        p_key_blob,
    );
    info!("SqlCryptExportKey called");
    // TODO: When implemented, if p_key_blob is NULL or p_key_blob.cb is too
    // small, set p_key_blob.cb to the required size and return
    // scp_err_InsufficientBuffer.  Never allocate memory on behalf of the caller.
    scp_err_NotSupported
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptImportKey(
    p_sess: *const SqlCpSession,
    p_key_name: *const SqlCpStr,
    key_decryptor_thumb: *const SqlCpKeyThumbprint,
    blob_type: SqlCpKeyBlobType,
    key_flags: SqlCpKeyFlags,
    p_key_blob: *const SqlCpKeyBlob,
) -> SqlCpError {
    let _ = (
        p_sess,
        p_key_name,
        key_decryptor_thumb,
        blob_type,
        key_flags,
        p_key_blob,
    );
    info!("SqlCryptImportKey called");
    scp_err_NotSupported
}

// ---------------------------------------------------------------------------
// Encryption / Decryption
// ---------------------------------------------------------------------------

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptEncrypt(
    p_sess: *const SqlCpSession,
    p_key_thumb: *const SqlCpKeyThumbprint,
    f_final: BOOLEAN,
    p_encrypt_params: *const SqlCpEncryptionParam,
    c_encrypt_params: ULONG,
    p_data_plain_text: *const SqlCpData,
    p_data_ciphertext: *mut SqlCpData,
) -> SqlCpError {
    let _ = (
        p_sess,
        p_key_thumb,
        f_final,
        p_encrypt_params,
        c_encrypt_params,
        p_data_plain_text,
        p_data_ciphertext,
    );
    info!("SqlCryptEncrypt called");
    scp_err_NotSupported
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptDecrypt(
    p_sess: *const SqlCpSession,
    p_key_thumb: *const SqlCpKeyThumbprint,
    f_final: BOOLEAN,
    p_encrypt_params: *const SqlCpEncryptionParam,
    c_encrypt_params: ULONG,
    p_data_ciphertext: *const SqlCpData,
    p_data_plain_text: *mut SqlCpData,
) -> SqlCpError {
    let _ = (
        p_sess,
        p_key_thumb,
        f_final,
        p_encrypt_params,
        c_encrypt_params,
        p_data_ciphertext,
        p_data_plain_text,
    );
    info!("SqlCryptDecrypt called");
    scp_err_NotSupported
}
