#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use std::sync::{
    Mutex, OnceLock,
    atomic::{AtomicU32, Ordering},
};
use tracing::{debug, error, info, warn};
use tracing_appender::non_blocking::WorkerGuard;

mod config;
mod kms_client;
mod session_store;
use session_store::{SessionCredential, SessionStore};
// SqlCpError enum variants generated by bindgen from sqlcrypt.h
use SqlCpError::{
    scp_err_InsufficientBuffer, scp_err_InvalidArgument, scp_err_NotFound, scp_err_NotSupported,
    scp_err_Success,
};

// UTF-16 LE encoding of "Cosmian KMS EKM Provider".
// Per the SQL Crypto API spec, SqlCpStr.ws does NOT need to be
// null-terminated; the `cb` field (byte count) is the sole length authority.
// We include a trailing 0x0000 anyway as a safety measure in case any
// internal SQL Server code path reads past `cb`, but it must NOT be counted
// in `cb`.  The slice lives for the lifetime of this DLL load.
static PROVIDER_NAME_UTF16: &[u16] = &[
    0x43, 0x6F, 0x73, 0x6D, 0x69, 0x61, 0x6E, // C o s m i a n
    0x20, //  (space)
    0x4B, 0x4D, 0x53, // K M S
    0x20, //  (space)
    0x45, 0x4B, 0x4D, // E K M
    0x20, //  (space)
    0x50, 0x72, 0x6F, 0x76, 0x69, 0x64, 0x65, 0x72,   // P r o v i d e r
    0x0000, // safety null — NOT counted in cb
];
// Character count of the string proper (excludes the safety null above).
const PROVIDER_NAME_CHARS: usize = 24;

// Bindgen-generated types from sqlcrypt.h
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// ---------------------------------------------------------------------------
// Session management — types and global state
// ---------------------------------------------------------------------------

/// Monotonically-increasing session-ID source.  Starts at 1 so that 0 can
/// serve as a "no session" sentinel (matching x_scp_KeyIdBad / x_SessionIdBad
/// conventions in the Microsoft sample).
static SESSION_COUNTER: AtomicU32 = AtomicU32::new(1);

/// Global session store: manages TTL, stale eviction, and the background
/// collector thread.  Initialised once inside `SqlCryptInitializeProvider`.
///
/// Defaults (overridden by `%PROGRAMDATA%\Cosmian\EKM\config.toml`):
/// 30-minute session max-age, collector runs every 2 minutes.
static SESSION_STORE: OnceLock<SessionStore> = OnceLock::new();

fn session_store() -> &'static SessionStore {
    SESSION_STORE.get_or_init(|| {
        let cfg = config::EkmConfig::load();
        SessionStore::new(cfg.max_age_seconds, cfg.stale_collector_period_seconds)
    })
}

/// Extract the numeric session ID stored as an opaque pointer in `SqlCpSession`.
/// Returns 0 (`x_SessionIdBad`) when the pointer is null.
fn session_id_of(p_sess: *const SqlCpSession) -> u32 {
    if p_sess.is_null() {
        0
    } else {
        unsafe { *p_sess as usize as u32 }
    }
}

/// Copy the raw UTF-16LE bytes out of a `SqlCpStr`.
///
/// # Safety
/// `s.ws` must be valid for `s.cb` bytes if non-null.
unsafe fn copy_sqlcp_str_bytes(s: &SqlCpStr) -> Vec<u8> {
    if s.ws.is_null() || s.cb == 0 {
        return Vec::new();
    }
    unsafe { std::slice::from_raw_parts(s.ws as *const u8, s.cb as usize).to_vec() }
}

/// Convert a `SqlCpStr` to a Rust `String` by copying the bytes and decoding as UTF-16LE.
///
/// # Safety
/// `s.ws` must be valid for `s.cb` bytes if non-null, and the bytes must be valid UTF-16LE.
unsafe fn sql_cp_str_to_string(s: &SqlCpStr) -> String {
    let bytes = unsafe { copy_sqlcp_str_bytes(s) };
    String::from_utf16_lossy(
        &bytes
            .chunks_exact(2)
            .map(|chunk| u16::from_le_bytes([chunk[0], chunk[1]]))
            .collect::<Vec<u16>>(),
    )
}

// ---------------------------------------------------------------------------
// Algorithm table
// ---------------------------------------------------------------------------

/// Canonical algorithm IDs exposed by this provider to SQL Server.
/// The discriminant values are the `SqlCpAlgId` (ULONG) passed to/from SQL.
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum EkmAlgId {
    Rsa2048 = 1,
    Rsa3072 = 2,
    Rsa4096 = 3,
    Aes128 = 4,
    Aes192 = 5,
    Aes256 = 6,
}

struct AlgEntry {
    id: u32,
    name: &'static str,
    /// UTF-16 tag characters (no null terminator); e.g. "RSA_2048".
    tag: &'static [u16],
    key_type: SqlCpKeyType,
    bit_len: u32,
    /// IV length in bits (0 for asymmetric algorithms).
    iv_len: u32,
}

// UTF-16 tag strings — each char is ASCII so the u16 value equals the byte value.
static TAG_RSA_2048: &[u16] = &[
    'R' as u16, 'S' as u16, 'A' as u16, '_' as u16, '2' as u16, '0' as u16, '4' as u16, '8' as u16,
];
static TAG_RSA_3072: &[u16] = &[
    'R' as u16, 'S' as u16, 'A' as u16, '_' as u16, '3' as u16, '0' as u16, '7' as u16, '2' as u16,
];
static TAG_RSA_4096: &[u16] = &[
    'R' as u16, 'S' as u16, 'A' as u16, '_' as u16, '4' as u16, '0' as u16, '9' as u16, '6' as u16,
];
static TAG_AES_128: &[u16] = &[
    'A' as u16, 'E' as u16, 'S' as u16, '_' as u16, '1' as u16, '2' as u16, '8' as u16,
];
static TAG_AES_192: &[u16] = &[
    'A' as u16, 'E' as u16, 'S' as u16, '_' as u16, '1' as u16, '9' as u16, '2' as u16,
];
static TAG_AES_256: &[u16] = &[
    'A' as u16, 'E' as u16, 'S' as u16, '_' as u16, '2' as u16, '5' as u16, '6' as u16,
];

static ALG_TABLE: &[AlgEntry] = &[
    AlgEntry {
        id: EkmAlgId::Rsa2048 as u32,
        name: "RSA_2048",
        tag: TAG_RSA_2048,
        key_type: SqlCpKeyType::scp_kt_Asymmetric,
        bit_len: 2048,
        iv_len: 0,
    },
    AlgEntry {
        id: EkmAlgId::Rsa3072 as u32,
        name: "RSA_3072",
        tag: TAG_RSA_3072,
        key_type: SqlCpKeyType::scp_kt_Asymmetric,
        bit_len: 3072,
        iv_len: 0,
    },
    AlgEntry {
        id: EkmAlgId::Rsa4096 as u32,
        name: "RSA_4096",
        tag: TAG_RSA_4096,
        key_type: SqlCpKeyType::scp_kt_Asymmetric,
        bit_len: 4096,
        iv_len: 0,
    },
    AlgEntry {
        id: EkmAlgId::Aes128 as u32,
        name: "AES_128",
        tag: TAG_AES_128,
        key_type: SqlCpKeyType::scp_kt_Symmetric,
        bit_len: 128,
        iv_len: 128,
    },
    AlgEntry {
        id: EkmAlgId::Aes192 as u32,
        name: "AES_192",
        tag: TAG_AES_192,
        key_type: SqlCpKeyType::scp_kt_Symmetric,
        bit_len: 192,
        iv_len: 128,
    },
    AlgEntry {
        id: EkmAlgId::Aes256 as u32,
        name: "AES_256",
        tag: TAG_AES_256,
        key_type: SqlCpKeyType::scp_kt_Symmetric,
        bit_len: 256,
        iv_len: 128,
    },
];

// ---------------------------------------------------------------------------
// Logging
//
// The rolling log file is written to:
//   %PROGRAMDATA%\Cosmian\EKM\logs\cosmian_ekm.log.<date>
// which on a typical Windows installation resolves to:
//   C:\ProgramData\Cosmian\EKM\logs\cosmian_ekm.log.<date>
//
// %PROGRAMDATA% is the correct root for a Windows service / DLL because
// SQL Server runs as a service account that has no user profile — only
// the machine-wide ProgramData directory is reliably writable.
//
// The companion configuration file should be placed at:
//   %PROGRAMDATA%\Cosmian\EKM\config.toml
// ---------------------------------------------------------------------------

/// Holds the `WorkerGuard` that keeps the non-blocking writer's background
/// thread alive.  Dropped (flushing all pending records) in
/// `SqlCryptFreeProvider`.
///
/// SQL Server may load and unload this DLL at its own discretion.  Each load
/// produces a fresh process image of the DLL with freshly-initialised statics,
/// so `OnceLock` naturally re-initialises on every DLL load without any
/// special handling.
static LOG_GUARD: OnceLock<Mutex<Option<WorkerGuard>>> = OnceLock::new();

/// Initialise the rolling-file subscriber exactly once.
/// Subsequent calls are no-ops.
fn init_logging() {
    // OnceLock::get_or_init guarantees the closure runs at most once even
    // under concurrent calls (e.g. two threads calling the provider entry
    // point simultaneously).
    LOG_GUARD.get_or_init(|| {
        // Resolve %PROGRAMDATA% at runtime so the code works regardless of
        // the Windows installation drive.
        let log_dir = std::env::var("PROGRAMDATA")
            .map(|p| {
                std::path::PathBuf::from(p)
                    .join("Cosmian")
                    .join("EKM")
                    .join("logs")
            })
            .unwrap_or_else(|_| std::path::PathBuf::from(r"C:\ProgramData\Cosmian\EKM\logs"));

        // Best-effort directory creation; if this fails the appender will
        // also fail and we fall through gracefully.
        let _ = std::fs::create_dir_all(&log_dir);

        let file_appender = tracing_appender::rolling::daily(&log_dir, "cosmian_ekm.log");
        let (non_blocking, guard) = tracing_appender::non_blocking(file_appender);

        tracing_subscriber::fmt()
            .with_writer(non_blocking)
            .with_max_level(tracing::Level::INFO)
            .with_ansi(false) // ANSI escape codes are meaningless in a plain log file
            .init();

        info!(
            log_dir = %log_dir.display(),
            "Cosmian EKM logging initialised"
        );

        Mutex::new(Some(guard))
    });
}

// ---------------------------------------------------------------------------
// Provider initialization
// ---------------------------------------------------------------------------

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptInitializeProvider() -> SqlCpError {
    init_logging();
    info!("SqlCryptInitializeProvider called");
    scp_err_Success
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptFreeProvider() -> SqlCpError {
    debug!("SqlCryptFreeProvider called");
    // Drop the WorkerGuard so the background logging thread flushes and exits
    // cleanly before the DLL is unloaded.
    if let Some(cell) = LOG_GUARD.get() {
        if let Ok(mut guard) = cell.lock() {
            drop(guard.take());
        }
    }
    info!("Cosmian EKM provider freed and logging shut down");
    scp_err_Success
}

// ---------------------------------------------------------------------------
// Session management
// ---------------------------------------------------------------------------

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptOpenSession(
    p_auth: *const SqlCpCredential,
    p_sess: *mut SqlCpSession,
) -> SqlCpError {
    debug!("SqlCryptOpenSession called");
    if p_sess.is_null() || p_auth.is_null() {
        return scp_err_InvalidArgument;
    }

    // Copy the credential strings before they go out of scope.
    let credential = unsafe {
        let auth = &*p_auth;
        SessionCredential {
            username: sql_cp_str_to_string(&auth.name),
            password: sql_cp_str_to_string(&auth.password),
        }
    };

    // Allocate a new session ID (non-zero, monotonically increasing).
    let session_id: u32 = SESSION_COUNTER.fetch_add(1, Ordering::Relaxed);

    info!(
        session_id,
        username_len = credential.username.len(),
        "SqlCryptOpenSession: new session"
    );

    session_store().insert(session_id, credential);

    // Write the session ID into the caller's handle slot.
    // SQL Server treats SqlCpSession as an opaque void*; we repurpose it as
    // a u32 widened to usize so the bit pattern survives the round-trip.
    unsafe {
        *p_sess = session_id as usize as SqlCpSession;
    }
    scp_err_Success
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptCloseSession(p_sess: *mut SqlCpSession, f_abort: BOOLEAN) -> SqlCpError {
    debug!("SqlCryptCloseSession called");
    if p_sess.is_null() {
        return scp_err_InvalidArgument;
    }
    let session_id = unsafe { *p_sess as usize as u32 };
    info!(
        session_id,
        abort = f_abort,
        "SqlCryptCloseSession: removing session"
    );
    session_store().remove(session_id);
    scp_err_Success
}

// ---------------------------------------------------------------------------
// Provider info
// ---------------------------------------------------------------------------

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptGetProviderInfo(p_provider_info: *mut SqlCpProviderInfo) -> SqlCpError {
    debug!("SqlCryptGetProviderInfo called");
    if p_provider_info.is_null() {
        return scp_err_InvalidArgument;
    }
    unsafe {
        let info = &mut *p_provider_info;

        // Name byte-count: 24 UTF-16 code units × 2 bytes = 48 bytes (no null terminator)
        let cb_name_required: ULONG = (PROVIDER_NAME_CHARS * size_of::<u16>()) as ULONG;

        // ---------------------------------------------------------------
        // Two-call buffer-negotiation protocol
        // (matches Microsoft USBCryptoProvider sample):
        //
        //   Call 1: SQL Server passes name.ws = NULL, name.cb = 0.
        //           Provider sets name.cb to the required byte count and
        //           returns scp_err_InsufficientBuffer.
        //
        //   Call 2: SQL Server passes name.ws = allocated buffer,
        //           name.cb = buffer size.  Provider fills the struct and
        //           copies the name string into the caller's buffer.
        // ---------------------------------------------------------------
        if info.name.cb < cb_name_required || info.name.ws.is_null() {
            info.name.cb = cb_name_required;
            debug!(
                required_cb = cb_name_required,
                caller_cb = info.name.cb,
                "SqlCryptGetProviderInfo: returning InsufficientBuffer (name buffer too small or NULL)"
            );
            return scp_err_InsufficientBuffer;
        }

        // Save the caller's name buffer pointer before overwriting the struct.
        let caller_name_ws = info.name.ws;

        // Build a local ProviderInfo with all the fixed fields.
        // We memcpy the whole struct (as the Microsoft sample does), then
        // restore the caller's ws pointer and copy the string in.
        let mut prov = std::mem::MaybeUninit::<SqlCpProviderInfo>::zeroed().assume_init();

        prov.name.cb = cb_name_required;
        prov.name.ws = PROVIDER_NAME_UTF16.as_ptr() as *mut WCHAR; // temporary, overwritten below

        // Stable GUID {C05A1A00-1001-4001-8001-000000000001}
        prov.guid.Data1 = 0xC05A_1A00u32;
        prov.guid.Data2 = 0x1001u16;
        prov.guid.Data3 = 0x4001u16;
        prov.guid.Data4 = [0x80, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01];

        prov.version.major = 1;
        prov.version.minor = 0;

        prov.scpVersion.major = 1;
        prov.scpVersion.minor = 1;

        prov.authType = SqlCpAuthType::scp_auth_Basic;
        prov.symmKeySupport = SqlCpKeyFlagsBm::scp_kf_Supported as SqlCpKeyFlags;
        prov.asymmKeySupport = SqlCpKeyFlagsBm::scp_kf_Supported as SqlCpKeyFlags;
        prov.cbKeyThumbLen = size_of::<GUID>() as ULONG; // 16
        prov.fAcceptsKeyName = 1; // TRUE

        // Copy the full struct into the caller's memory (overwrites name.ws)
        std::ptr::copy_nonoverlapping(&prov as *const SqlCpProviderInfo, p_provider_info, 1);

        // Restore the caller's name buffer pointer and copy the name string in
        let info = &mut *p_provider_info;
        info.name.ws = caller_name_ws;
        info.name.cb = cb_name_required;
        if cb_name_required > 0 {
            std::ptr::copy_nonoverlapping(
                PROVIDER_NAME_UTF16.as_ptr(),
                caller_name_ws as *mut u16,
                PROVIDER_NAME_CHARS,
            );
        }

        info!(
            struct_size = size_of::<SqlCpProviderInfo>(),
            name_cb = info.name.cb,
            name_ws_ptr = ?info.name.ws,
            guid_data1 = format_args!("0x{:08X}", info.guid.Data1),
            version = format_args!("{}.{}.{}.{}", info.version.major, info.version.minor, info.version.build, info.version.revision),
            scp_version = format_args!("{}.{}.{}.{}", info.scpVersion.major, info.scpVersion.minor, info.scpVersion.build, info.scpVersion.revision),
            auth_type = ?info.authType,
            symm = info.symmKeySupport,
            asymm = info.asymmKeySupport,
            thumb_len = info.cbKeyThumbLen,
            accepts_key_name = info.fAcceptsKeyName,
            "SqlCryptGetProviderInfo: "
        );
    }
    scp_err_Success
}

// ---------------------------------------------------------------------------
// Provider algorithms
// ---------------------------------------------------------------------------

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptGetNextAlgorithmId(p_alg_id: *mut SqlCpAlgId) -> SqlCpError {
    if p_alg_id.is_null() {
        return scp_err_InvalidArgument;
    }
    // SQL Server calls this repeatedly starting with *p_alg_id = 0
    // (x_scp_AlgIdBad).  The provider must set *p_alg_id to the next
    // algorithm ID strictly greater than the current value, or return
    // NotFound to signal end-of-list.
    let current = unsafe { *p_alg_id };
    match ALG_TABLE.iter().find(|e| e.id > current) {
        Some(entry) => {
            info!(
                current,
                next = entry.id,
                "SqlCryptGetNextAlgorithmId -> name: {}",
                entry.name
            );
            unsafe { *p_alg_id = entry.id };
            scp_err_Success
        }
        None => {
            info!(current, "SqlCryptGetNextAlgorithmId: end of list");
            scp_err_NotFound
        }
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptGetAlgorithmInfo(
    alg_id: SqlCpAlgId,
    p_algorithm_info: *mut SqlCpAlgorithmInfo,
) -> SqlCpError {
    debug!(alg_id, "SqlCryptGetAlgorithmInfo called");
    if p_algorithm_info.is_null() {
        return scp_err_InvalidArgument;
    }
    let Some(entry) = ALG_TABLE.iter().find(|e| e.id == alg_id) else {
        return scp_err_NotFound;
    };
    unsafe {
        let info = &mut *p_algorithm_info;
        let cb_tag_required = (entry.tag.len() * size_of::<u16>()) as ULONG;

        // Two-call buffer-negotiation for algTag.ws, matching the Microsoft
        // USBCryptoProvider pattern exactly:
        //
        //   Call 1: SQL Server passes algTag.ws = NULL, algTag.cb = 0.
        //           Provider sets algTag.cb = required bytes and returns
        //           scp_err_InsufficientBuffer.
        //   Call 2: SQL Server passes an allocated buffer.  Provider copies
        //           the full struct into the caller's memory, restores the
        //           caller's algTag.ws pointer, then copies the tag string in.
        if info.algTag.cb < cb_tag_required || info.algTag.ws.is_null() {
            info.algTag.cb = cb_tag_required;
            debug!(
                alg_id,
                required_cb = cb_tag_required,
                caller_cb = info.algTag.cb,
                "SqlCryptGetAlgorithmInfo: returning InsufficientBuffer (tag buffer too small or NULL)"
            );
            return scp_err_InsufficientBuffer;
        }

        // Save the caller's tag buffer pointer before the struct copy overwrites it.
        let caller_tag_ws = info.algTag.ws;

        // Build a local SqlCpAlgorithmInfo with all fields set, including padding.
        // `type` is a Rust keyword; bindgen renames the C field to `type_`.
        let mut src = std::mem::MaybeUninit::<SqlCpAlgorithmInfo>::zeroed().assume_init();
        src.algId = entry.id;
        src.algTag.cb = cb_tag_required;
        src.algTag.ws = entry.tag.as_ptr() as *mut WCHAR; // temporary; overwritten below
        src.type_ = entry.key_type;
        src.bitLen = entry.bit_len;
        src.ivLen = entry.iv_len;

        // Copy the full struct into the caller's memory (all fields + padding),
        // matching the Microsoft `memcpy(pAlgorithmInfo, &x_AlgInfos[i], sizeof(*pAlgorithmInfo))`.
        std::ptr::copy_nonoverlapping(&src as *const SqlCpAlgorithmInfo, p_algorithm_info, 1);

        // Restore the caller's tag buffer pointer and copy the tag string into it,
        // matching `pAlgorithmInfo->algTag.ws = wsTag; memcpy(algTag.ws, ..., cb)`.
        let info = &mut *p_algorithm_info;
        info.algTag.ws = caller_tag_ws;
        if cb_tag_required > 0 {
            std::ptr::copy_nonoverlapping(
                entry.tag.as_ptr(),
                caller_tag_ws as *mut u16,
                entry.tag.len(),
            );
        }
        info!(
            alg_id,
            tag = entry.name,
            key_type = format_args!("{:?}", entry.key_type),
            bit_len = entry.bit_len,
            iv_len = entry.iv_len,
            "SqlCryptGetAlgorithmInfo: algorithm info populated (second call)"
        );
    }
    scp_err_Success
}

// ---------------------------------------------------------------------------
// Key management
// ---------------------------------------------------------------------------

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptCreateKey(
    p_sess: *const SqlCpSession,
    p_key_name: *const SqlCpStr,
    algid: SqlCpAlgId,
    _key_flags: SqlCpKeyFlags,
    p_key_thumb: *mut SqlCpKeyThumbprint,
) -> SqlCpError {
    let session_id = session_id_of(p_sess);
    if p_key_name.is_null() || p_key_thumb.is_null() || p_sess.is_null() {
        return scp_err_InvalidArgument;
    }

    let key_name = unsafe { sql_cp_str_to_string(&*p_key_name) };
    info!(
        session_id,
        algid,
        key_name = %key_name,
        "SqlCryptCreateKey called"
    );

    // Look up the algorithm in our table.
    let Some(alg) = ALG_TABLE.iter().find(|e| e.id == algid) else {
        warn!(session_id, algid, "SqlCryptCreateKey: unknown algorithm ID");
        return scp_err_NotFound;
    };

    let is_symmetric = alg.key_type == SqlCpKeyType::scp_kt_Symmetric;

    // Retrieve the session's username for certificate lookup.
    let username = match session_store().with_session(session_id, |cred| cred.username.clone()) {
        Some(name) => name,
        None => {
            warn!(session_id, "SqlCryptCreateKey: session not found or stale");
            return scp_err_NotFound;
        }
    };

    // Load configuration (KMS section required).
    let ekm_config = config::EkmConfig::load();
    if ekm_config.kms.server_url.is_none() {
        error!(
            session_id,
            "SqlCryptCreateKey: kms.server_url not configured in config.toml"
        );
        return scp_err_NotSupported;
    }

    // Create the key on the Cosmian KMS via mTLS.
    match kms_client::create_key(
        &ekm_config.kms,
        &username,
        &key_name,
        is_symmetric,
        alg.bit_len,
    ) {
        Ok(thumb_bytes) => {
            // Write the 16-byte thumbprint into the caller's buffer.
            unsafe {
                let thumb = &mut *p_key_thumb;
                let len = thumb_bytes.len().min(thumb.cb as usize);
                std::ptr::copy_nonoverlapping(thumb_bytes.as_ptr(), thumb.pb, len);
                thumb.cb = len as ULONG;
            }
            info!(
                session_id,
                key_name = %key_name,
                alg = alg.name,
                "SqlCryptCreateKey: key created successfully"
            );
            scp_err_Success
        }
        Err(e) => {
            error!(
                session_id,
                key_name = %key_name,
                error = %e,
                "SqlCryptCreateKey: KMS key creation failed"
            );
            scp_err_NotSupported
        }
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptDropKey(
    p_sess: *const SqlCpSession,
    p_key_thumb: *const SqlCpKeyThumbprint,
) -> SqlCpError {
    let session_id = session_id_of(p_sess);
    let _ = p_key_thumb;
    info!(session_id, "SqlCryptDropKey called");
    scp_err_NotSupported
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptGetNextKeyId(
    p_sess: *const SqlCpSession,
    p_key_id: *mut SqlCpKeyId,
) -> SqlCpError {
    let session_id = session_id_of(p_sess);
    let _ = p_key_id;
    info!(session_id, "SqlCryptGetNextKeyId called");
    // Return NotFound to signal an empty key enumeration (no keys provisioned yet).
    scp_err_NotFound
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptGetKeyInfoByKeyId(
    p_sess: *const SqlCpSession,
    key_id: SqlCpKeyId,
    p_key_info: *mut SqlCpKeyInfo,
) -> SqlCpError {
    let session_id = session_id_of(p_sess);
    let _ = (key_id, p_key_info);
    info!(session_id, "SqlCryptGetKeyInfoByKeyId called");
    // TODO: When implemented, follow the memory-management contract:
    // If p_key_info is NULL or the embedded SqlCpStr buffers are too small,
    // populate the `cb` fields with the required byte counts and return
    // scp_err_InsufficientBuffer.  Never allocate on behalf of the caller.
    scp_err_NotSupported
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptGetKeyInfoByThumb(
    p_sess: *const SqlCpSession,
    p_key_thumb: *const SqlCpKeyThumbprint,
    p_key_info: *mut SqlCpKeyInfo,
) -> SqlCpError {
    let session_id = session_id_of(p_sess);
    let _ = (p_key_thumb, p_key_info);
    info!(session_id, "SqlCryptGetKeyInfoByThumb called");
    // TODO: same InsufficientBuffer contract as GetKeyInfoByKeyId.
    scp_err_NotSupported
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptGetKeyInfoByName(
    p_sess: *const SqlCpSession,
    p_key_name: *const SqlCpStr,
    p_key_info: *mut SqlCpKeyInfo,
) -> SqlCpError {
    let session_id = session_id_of(p_sess);
    let _ = (p_key_name, p_key_info);
    info!(session_id, "SqlCryptGetKeyInfoByName called");
    // TODO: same InsufficientBuffer contract as GetKeyInfoByKeyId.
    scp_err_NotSupported
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptExportKey(
    p_sess: *const SqlCpSession,
    p_key_thumb: *const SqlCpKeyThumbprint,
    key_encryptor_thumb: *const SqlCpKeyThumbprint,
    blob_type: SqlCpKeyBlobType,
    p_key_blob: *mut SqlCpKeyBlob,
) -> SqlCpError {
    let session_id = session_id_of(p_sess);
    let _ = (p_key_thumb, key_encryptor_thumb, blob_type, p_key_blob);
    info!(session_id, "SqlCryptExportKey called");
    // TODO: When implemented, if p_key_blob is NULL or p_key_blob.cb is too
    // small, set p_key_blob.cb to the required size and return
    // scp_err_InsufficientBuffer.  Never allocate memory on behalf of the caller.
    scp_err_NotSupported
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptImportKey(
    p_sess: *const SqlCpSession,
    p_key_name: *const SqlCpStr,
    key_decryptor_thumb: *const SqlCpKeyThumbprint,
    blob_type: SqlCpKeyBlobType,
    key_flags: SqlCpKeyFlags,
    p_key_blob: *const SqlCpKeyBlob,
) -> SqlCpError {
    let session_id = session_id_of(p_sess);
    let _ = (
        p_key_name,
        key_decryptor_thumb,
        blob_type,
        key_flags,
        p_key_blob,
    );
    info!(session_id, "SqlCryptImportKey called");
    scp_err_NotSupported
}

// ---------------------------------------------------------------------------
// Encryption / Decryption
// ---------------------------------------------------------------------------

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptEncrypt(
    p_sess: *const SqlCpSession,
    p_key_thumb: *const SqlCpKeyThumbprint,
    f_final: BOOLEAN,
    p_encrypt_params: *const SqlCpEncryptionParam,
    c_encrypt_params: ULONG,
    p_data_plain_text: *const SqlCpData,
    p_data_ciphertext: *mut SqlCpData,
) -> SqlCpError {
    let session_id = session_id_of(p_sess);
    let _ = (
        p_key_thumb,
        f_final,
        p_encrypt_params,
        c_encrypt_params,
        p_data_plain_text,
        p_data_ciphertext,
    );
    info!(session_id, "SqlCryptEncrypt called");
    scp_err_NotSupported
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptDecrypt(
    p_sess: *const SqlCpSession,
    p_key_thumb: *const SqlCpKeyThumbprint,
    f_final: BOOLEAN,
    p_encrypt_params: *const SqlCpEncryptionParam,
    c_encrypt_params: ULONG,
    p_data_ciphertext: *const SqlCpData,
    p_data_plain_text: *mut SqlCpData,
) -> SqlCpError {
    let session_id = session_id_of(p_sess);
    let _ = (
        p_key_thumb,
        f_final,
        p_encrypt_params,
        c_encrypt_params,
        p_data_ciphertext,
        p_data_plain_text,
    );
    info!(session_id, "SqlCryptDecrypt called");
    scp_err_NotSupported
}
