#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::upper_case_acronyms)]

use std::sync::{Mutex, OnceLock};
use tracing::info;
use tracing_appender::non_blocking::WorkerGuard;
// SqlCpError enum variants generated by bindgen from sqlcrypt.h
use SqlCpError::{scp_err_NotSupported, scp_err_Success};

// Bindgen-generated types from sqlcrypt.h
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// ---------------------------------------------------------------------------
// Logging
//
// The rolling log file is written to:
//   %PROGRAMDATA%\Cosmian\EKM\logs\cosmian_ekm.log.<date>
// which on a typical Windows installation resolves to:
//   C:\ProgramData\Cosmian\EKM\logs\cosmian_ekm.log.<date>
//
// %PROGRAMDATA% is the correct root for a Windows service / DLL because
// SQL Server runs as a service account that has no user profile — only
// the machine-wide ProgramData directory is reliably writable.
//
// The companion configuration file should be placed at:
//   %PROGRAMDATA%\Cosmian\EKM\config.toml
// ---------------------------------------------------------------------------

/// Holds the `WorkerGuard` that keeps the non-blocking writer's background
/// thread alive.  Dropped (flushing all pending records) in
/// `SqlCryptFreeProvider`.
static LOG_GUARD: OnceLock<Mutex<Option<WorkerGuard>>> = OnceLock::new();

/// Initialise the rolling-file subscriber exactly once.
/// Subsequent calls are no-ops.
fn init_logging() {
    // OnceLock::get_or_init guarantees the closure runs at most once even
    // under concurrent calls (e.g. two threads calling the provider entry
    // point simultaneously).
    LOG_GUARD.get_or_init(|| {
        // Resolve %PROGRAMDATA% at runtime so the code works regardless of
        // the Windows installation drive.
        let log_dir = std::env::var("PROGRAMDATA")
            .map(|p| {
                std::path::PathBuf::from(p)
                    .join("Cosmian")
                    .join("EKM")
                    .join("logs")
            })
            .unwrap_or_else(|_| std::path::PathBuf::from(r"C:\ProgramData\Cosmian\EKM\logs"));

        // Best-effort directory creation; if this fails the appender will
        // also fail and we fall through gracefully.
        let _ = std::fs::create_dir_all(&log_dir);

        let file_appender = tracing_appender::rolling::daily(&log_dir, "cosmian_ekm.log");
        let (non_blocking, guard) = tracing_appender::non_blocking(file_appender);

        tracing_subscriber::fmt()
            .with_writer(non_blocking)
            .with_max_level(tracing::Level::INFO)
            .with_ansi(false) // ANSI escape codes are meaningless in a plain log file
            .init();

        info!(
            log_dir = %log_dir.display(),
            "Cosmian EKM logging initialised"
        );

        Mutex::new(Some(guard))
    });
}

// ---------------------------------------------------------------------------
// Provider initialization
// ---------------------------------------------------------------------------

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptInitializeProvider() -> SqlCpError {
    init_logging();
    info!("SqlCryptInitializeProvider called");
    scp_err_Success
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptFreeProvider() -> SqlCpError {
    info!("SqlCryptFreeProvider called");
    // Drop the WorkerGuard so the background logging thread flushes and exits
    // cleanly before the DLL is unloaded.
    if let Some(cell) = LOG_GUARD.get() {
        if let Ok(mut guard) = cell.lock() {
            drop(guard.take());
        }
    }
    scp_err_Success
}

// ---------------------------------------------------------------------------
// Session management
// ---------------------------------------------------------------------------

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptOpenSession(
    p_auth: *const SqlCpCredential,
    p_sess: *mut SqlCpSession,
) -> SqlCpError {
    let _ = (p_auth, p_sess);
    info!("SqlCryptOpenSession called");
    scp_err_NotSupported
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptCloseSession(p_sess: *mut SqlCpSession, f_abort: BOOLEAN) -> SqlCpError {
    let _ = (p_sess, f_abort);
    info!("SqlCryptCloseSession called");
    scp_err_NotSupported
}

// ---------------------------------------------------------------------------
// Provider info
// ---------------------------------------------------------------------------

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptGetProviderInfo(p_provider_info: *mut SqlCpProviderInfo) -> SqlCpError {
    let _ = p_provider_info;
    info!("SqlCryptGetProviderInfo called");
    scp_err_NotSupported
}

// ---------------------------------------------------------------------------
// Provider algorithms
// ---------------------------------------------------------------------------

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptGetNextAlgorithmId(p_alg_id: *mut SqlCpAlgId) -> SqlCpError {
    let _ = p_alg_id;
    info!("SqlCryptGetNextAlgorithmId called");
    scp_err_NotSupported
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptGetAlgorithmInfo(
    alg_id: SqlCpAlgId,
    p_algorithm_info: *mut SqlCpAlgorithmInfo,
) -> SqlCpError {
    let _ = (alg_id, p_algorithm_info);
    info!("SqlCryptGetAlgorithmInfo called");
    scp_err_NotSupported
}

// ---------------------------------------------------------------------------
// Key management
// ---------------------------------------------------------------------------

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptCreateKey(
    p_sess: *const SqlCpSession,
    p_key_name: *const SqlCpStr,
    algid: SqlCpAlgId,
    key_flags: SqlCpKeyFlags,
    p_key_thumb: *mut SqlCpKeyThumbprint,
) -> SqlCpError {
    let _ = (p_sess, p_key_name, algid, key_flags, p_key_thumb);
    info!("SqlCryptCreateKey called");
    scp_err_NotSupported
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptDropKey(
    p_sess: *const SqlCpSession,
    p_key_thumb: *const SqlCpKeyThumbprint,
) -> SqlCpError {
    let _ = (p_sess, p_key_thumb);
    info!("SqlCryptDropKey called");
    scp_err_NotSupported
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptGetNextKeyId(
    p_sess: *const SqlCpSession,
    p_key_id: *mut SqlCpKeyId,
) -> SqlCpError {
    let _ = (p_sess, p_key_id);
    info!("SqlCryptGetNextKeyId called");
    scp_err_NotSupported
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptGetKeyInfoByKeyId(
    p_sess: *const SqlCpSession,
    key_id: SqlCpKeyId,
    p_key_info: *mut SqlCpKeyInfo,
) -> SqlCpError {
    let _ = (p_sess, key_id, p_key_info);
    info!("SqlCryptGetKeyInfoByKeyId called");
    scp_err_NotSupported
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptGetKeyInfoByThumb(
    p_sess: *const SqlCpSession,
    p_key_thumb: *const SqlCpKeyThumbprint,
    p_key_info: *mut SqlCpKeyInfo,
) -> SqlCpError {
    let _ = (p_sess, p_key_thumb, p_key_info);
    info!("SqlCryptGetKeyInfoByThumb called");
    scp_err_NotSupported
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptGetKeyInfoByName(
    p_sess: *const SqlCpSession,
    p_key_name: *const SqlCpStr,
    p_key_info: *mut SqlCpKeyInfo,
) -> SqlCpError {
    let _ = (p_sess, p_key_name, p_key_info);
    info!("SqlCryptGetKeyInfoByName called");
    scp_err_NotSupported
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptExportKey(
    p_sess: *const SqlCpSession,
    p_key_thumb: *const SqlCpKeyThumbprint,
    key_encryptor_thumb: *const SqlCpKeyThumbprint,
    blob_type: SqlCpKeyBlobType,
    p_key_blob: *mut SqlCpKeyBlob,
) -> SqlCpError {
    let _ = (
        p_sess,
        p_key_thumb,
        key_encryptor_thumb,
        blob_type,
        p_key_blob,
    );
    info!("SqlCryptExportKey called");
    scp_err_NotSupported
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptImportKey(
    p_sess: *const SqlCpSession,
    p_key_name: *const SqlCpStr,
    key_decryptor_thumb: *const SqlCpKeyThumbprint,
    blob_type: SqlCpKeyBlobType,
    key_flags: SqlCpKeyFlags,
    p_key_blob: *const SqlCpKeyBlob,
) -> SqlCpError {
    let _ = (
        p_sess,
        p_key_name,
        key_decryptor_thumb,
        blob_type,
        key_flags,
        p_key_blob,
    );
    info!("SqlCryptImportKey called");
    scp_err_NotSupported
}

// ---------------------------------------------------------------------------
// Encryption / Decryption
// ---------------------------------------------------------------------------

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptEncrypt(
    p_sess: *const SqlCpSession,
    p_key_thumb: *const SqlCpKeyThumbprint,
    f_final: BOOLEAN,
    p_encrypt_params: *const SqlCpEncryptionParam,
    c_encrypt_params: ULONG,
    p_data_plain_text: *const SqlCpData,
    p_data_ciphertext: *mut SqlCpData,
) -> SqlCpError {
    let _ = (
        p_sess,
        p_key_thumb,
        f_final,
        p_encrypt_params,
        c_encrypt_params,
        p_data_plain_text,
        p_data_ciphertext,
    );
    info!("SqlCryptEncrypt called");
    scp_err_NotSupported
}

#[unsafe(no_mangle)]
pub extern "C" fn SqlCryptDecrypt(
    p_sess: *const SqlCpSession,
    p_key_thumb: *const SqlCpKeyThumbprint,
    f_final: BOOLEAN,
    p_encrypt_params: *const SqlCpEncryptionParam,
    c_encrypt_params: ULONG,
    p_data_ciphertext: *const SqlCpData,
    p_data_plain_text: *mut SqlCpData,
) -> SqlCpError {
    let _ = (
        p_sess,
        p_key_thumb,
        f_final,
        p_encrypt_params,
        c_encrypt_params,
        p_data_ciphertext,
        p_data_plain_text,
    );
    info!("SqlCryptDecrypt called");
    scp_err_NotSupported
}
